Fix url-download
Fix error of download youtube-dl, required in PowderPlayer for work, screenshot ->  https://ibb.co/QPLbPny

----------------------------------------------------------------------------------------------------------------
> youtube-dl@1.11.2 postinstall /home/linux/PowderPlayer/node_modules/youtube-dl
> node ./scripts/download.js

Error: Could not find download link in https://rg3.github.io/youtube-dl/download.html
    at Request.get [as _callback] (/home/linux/PowderPlayer/node_modules/youtube-dl/lib/downloader.js:64:31)
    at Request.self.callback (/home/linux/PowderPlayer/node_modules/youtube-dl/node_modules/request/request.js:200:22)...